// Generated by gencpp from file path_follower/GetPath.msg
// DO NOT EDIT!


#ifndef PATH_FOLLOWER_MESSAGE_GETPATH_H
#define PATH_FOLLOWER_MESSAGE_GETPATH_H

#include <ros/service_traits.h>


#include <path_follower/GetPathRequest.h>
#include <path_follower/GetPathResponse.h>


namespace path_follower
{

struct GetPath
{

typedef GetPathRequest Request;
typedef GetPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPath
} // namespace path_follower


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_follower::GetPath > {
  static const char* value()
  {
    return "58d6f138c7de7ef47c75d4b7e5df5472";
  }

  static const char* value(const ::path_follower::GetPath&) { return value(); }
};

template<>
struct DataType< ::path_follower::GetPath > {
  static const char* value()
  {
    return "path_follower/GetPath";
  }

  static const char* value(const ::path_follower::GetPath&) { return value(); }
};


// service_traits::MD5Sum< ::path_follower::GetPathRequest> should match 
// service_traits::MD5Sum< ::path_follower::GetPath > 
template<>
struct MD5Sum< ::path_follower::GetPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_follower::GetPath >::value();
  }
  static const char* value(const ::path_follower::GetPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_follower::GetPathRequest> should match 
// service_traits::DataType< ::path_follower::GetPath > 
template<>
struct DataType< ::path_follower::GetPathRequest>
{
  static const char* value()
  {
    return DataType< ::path_follower::GetPath >::value();
  }
  static const char* value(const ::path_follower::GetPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_follower::GetPathResponse> should match 
// service_traits::MD5Sum< ::path_follower::GetPath > 
template<>
struct MD5Sum< ::path_follower::GetPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_follower::GetPath >::value();
  }
  static const char* value(const ::path_follower::GetPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_follower::GetPathResponse> should match 
// service_traits::DataType< ::path_follower::GetPath > 
template<>
struct DataType< ::path_follower::GetPathResponse>
{
  static const char* value()
  {
    return DataType< ::path_follower::GetPath >::value();
  }
  static const char* value(const ::path_follower::GetPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_FOLLOWER_MESSAGE_GETPATH_H
